// Generated by CoffeeScript 1.10.0
(function() {
  var coffeelint, gulp;

  gulp = require('gulp');

  coffeelint = require('gulp-coffeelint');

  gulp.task('lint', function() {
    return gulp.src('./lib/*.coffee').pipe(coffeelint('coffeelint.json')).pipe(coffeelint.reporter('default'));
  });

}).call(this);
